name: Build And Test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build And Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # This is the crucial step. We do NOT start services here.
      # Your tests, using Testcontainers, will read the docker-compose.yml file
      # and start the services automatically. Your application code will then connect
      # to 'localhost' on the ports mapped in the compose file.
      - name: Build and Test with Gradle
        run: ./gradlew build --no-daemon

      # If tests fail, it's useful to see the state of docker containers
      # that Testcontainers may have left running.
      - name: Show Docker status on failure
        if: failure()
        run: |
          echo "--- Docker PS ---"
          docker ps -a
          echo "--- Docker Compose Logs ---"
          docker compose logs
