name: Build And Test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build And Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 1

      - name: Start Services
        run: docker compose up -d --wait

      - name: Set up JDK 21
        uses: actions/setup-java@v4.7.1
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.3.1

      - name: Restore Gradle Build Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Build and Test with Gradle
        run: ./gradlew build --no-daemon --parallel --build-cache --scan

      - name: Stop Services
        if: always()
        run: docker compose down
