name: Build And Test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build And Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 1

      - name: Set up JDK 21
        uses: actions/setup-java@v5.0.0
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.4.2

      - name: Build and Test with Gradle
        run: ./gradlew build --no-daemon

      - name: Show Docker status on failure
        if: failure()
        run: |
          echo "--- Docker PS ---"
          docker ps -a
          echo "--- Docker Compose Logs ---"
          docker compose logs
